default: GetBigPic.class GetOnePic.class Group_List.class SQLServlet.class UploadImage.class DeletePic.class add_Friend.class delete_Group.class remove_Friend.class


add_Friend.class: add_Friend.java
		javac add_Friend.java

delete_Group.class: delete_Group.java
		javac delete_Group.java

DeletePic.class: DeletePic.java
		javac DeletePic.java

GetBigPic.class: GetBigPic.java
		javac GetBigPic.java

GetOnePic.class: GetOnePic.java
		javac GetOnePic.java

Group_List.class: Group_List.java
		javac Group_List.java

remove_Friend.class: remove_Friend.java
		javac remove_Friend.java

SQLServlet.class: SQLServlet.java
		javac SQLServlet.java

UploadImage.class: UploadImage.java
		javac UploadImage.java

clean:
	rm *.class
